// MEngine Preprocessor helper macro definitions
#pragma once

#ifndef MENGINE_PREPROC_HELPERS
#define MENGINE_PREPROC_HELPERS

// TODO
#include "HAL/PlatformHeader.h"

#define PREPROC_TO_STR(x) PREPROC_TO_STR_INNER(x)
#define PREPROC_TO_STR_INNER(x) #x

#define PREPROC_ASSEMBLE_STR(x, y) PREPROC_ASSEMBLE_STR_INNER(x, y)
#define PREPROC_ASSEMBLE_STR_INNER(x, y) x ## y

#define PLATFORM_HEADER(Suffix) PREPROC_TO_STR(PREPROC_ASSEMBLE_STR(PLATFORM_HEADER_NAME/PLATFORM_HEADER_NAME, Suffix))

#endif // MENGINE_PREPROC_HELPERS