#pragma once

#ifndef _ME_APP_APPLICATION_PLATFORM_APPLICATION_ACCESS_PORT_
#define _ME_APP_APPLICATION_PLATFORM_APPLICATION_ACCESS_PORT_

#include "HAL/Platform.h"

#include PLATFORM_HEADER(PlatformApplicationAccessPort.h)

#endif // _ME_APP_APPLICATION_PLATFORM_APPLICATION_ACCESS_PORT_